"""
ODE Regression Module for LTX-2 Causal Model Initialization.

Implements the ODE initialization stage described in CausVid paper Section 4.3
(https://arxiv.org/abs/2412.07772), adapted for LTX-2's audio-video joint generation.

Training Process:
1. Load precomputed ODE trajectories (generated by bidirectional teacher model)
2. Train causal model to regress clean samples from noisy inputs
3. Use as initialization for subsequent Self-Forcing DMD distillation

Key Adaptation for LTX-2:
- Supports joint audio-video latent regression
- Uses LTX-2's velocity prediction formulation
- Handles audio-video temporal alignment (3 fps video ↔ 25 fps audio)
"""

from typing import Tuple, Dict, Any, Optional
from dataclasses import dataclass

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.distributed as dist

from ltx_causal.attention.mask_builder import compute_av_blocks


@dataclass
class ODERegressionConfig:
    """
    Configuration for ODE regression training.

    Weight Loading Options:
    1. causal_model_checkpoint: Load existing causal model checkpoint
    2. bidirectional_model_checkpoint: Load bidirectional DMD-distilled model,
       then convert to causal (weights are compatible)
    3. checkpoint_path: Load the original LTX-2 diffusion checkpoint as fallback

    Typical workflow:
        Stage 0: Train bidirectional DMD → bidirectional_checkpoint
        Stage 1: ODE Init with bidirectional_model_checkpoint → causal_checkpoint
        Stage 2: Self-Forcing with causal_checkpoint → final model
    """

    # Model paths
    checkpoint_path: str = ""                             # LTX-2 base checkpoint (required for text encoder)
    causal_model_checkpoint: Optional[str] = None         # Pre-trained causal model
    bidirectional_model_checkpoint: Optional[str] = None  # From Stage 0 DMD
    text_encoder_checkpoint: str = ""                     # Gemma text encoder path

    # Denoising timesteps (from noise to clean)
    # Default: 4 key timesteps matching CausVid
    denoising_step_list: Tuple[int, ...] = (1000, 757, 522, 0)

    # Training task
    generator_task: str = "causal_video"  # "causal_video" or "bidirectional_video"

    # Causal generation settings
    num_frame_per_block: int = 3

    # Model settings
    gradient_checkpointing: bool = True
    mixed_precision: bool = True
    text_encoder_device: str = "cuda"
    video_height: int = 512
    video_width: int = 768

    # Whether to use the same timestep for all frames (easier task for training)
    # True:  all frames use the same random noise level (like bidirectional)
    # False: each block uses an independent random noise level (full causal)
    uniform_timestep: bool = False

    # Loss target: always x0 (wrapper converts velocity→x0 internally).
    # Kept for backward config compatibility; value is ignored.
    loss_target: str = "x0"

    # Ablation: disable causal mask (fully bidirectional = original LTX-2)
    disable_causal_mask: bool = False

    # Log-ratio entropy-aligned rescaling for causal attention outputs.
    # When true, each token's causal attention output is scaled by
    # log(1 + visible_tokens) / log(1 + total_tokens).
    # No learnable parameters — purely structural rescaling.
    enable_causal_log_rescale: bool = False

    # Block 0 video frames (4-3-3-3-... layout). Block 0 has
    # num_frame_per_block_first video frames + AUDIO_FRAMES_FIRST_BLOCK audio.
    num_frame_per_block_first: int = 4

    # Loss weights for combining video and audio losses.
    # loss = video_loss_weight * video_loss + audio_loss_weight * audio_loss
    # Set audio_loss_weight=0 to train video-only (current default behavior).
    video_loss_weight: float = 1.0
    audio_loss_weight: float = 0.0

    # Refuse legacy/default architecture fallbacks when training from LTX-2.3.
    require_ltx23_architecture: bool = True
    trainable_fp8_mode: str = "training"


class LTX2ODERegression(nn.Module):
    """
    ODE Regression module for LTX-2 causal model initialization.

    This module:
    1. Takes precomputed ODE trajectories (noise→clean)
    2. Randomly samples intermediate timesteps
    3. Trains the causal generator to predict clean latents

    The loss is MSE between predicted clean latents and target clean latents.

    Example:
        config = ODERegressionConfig(
            causal_model_checkpoint="path/to/checkpoint",
            text_encoder_checkpoint="path/to/gemma",
        )
        module = LTX2ODERegression(config, device="cuda")

        # Training step
        loss, log_dict = module.generator_loss(
            video_latent=video_ode_trajectory,  # [B, T, F, C, H, W]
            audio_latent=audio_ode_trajectory,  # [B, T, F_a, C]
            conditional_dict=text_embeddings,
        )
    """

    def __init__(
        self,
        config: ODERegressionConfig,
        device: torch.device | str = "cuda",
    ):
        super().__init__()
        self.config = config
        self.device = torch.device(device)
        self.dtype = torch.bfloat16 if config.mixed_precision else torch.float32

        # Denoising timesteps
        self.denoising_step_list = torch.tensor(
            config.denoising_step_list,
            dtype=torch.long,
            device=self.device,
        )

        self.num_frame_per_block = config.num_frame_per_block

        # Rank-0 printing helper
        self._is_main = not dist.is_initialized() or dist.get_rank() == 0

        # Lazy model loading
        self._generator = None
        self._text_encoder = None

        # Diagnostic logger (set by ODETrainer for rank 0)
        self.diag_logger = None
        self._diag_step = 0

    def _print(self, *args, **kwargs):
        """Print only on rank 0 in distributed training."""
        if self._is_main:
            print(*args, **kwargs)

    def _make_model_config(self):
        """Create CausalLTXModelConfig from ODE config (avoids repetition)."""
        from ltx_causal import CausalLTXModelConfig

        checkpoint_config = self._load_checkpoint_config(self.config.checkpoint_path)
        if self.config.require_ltx23_architecture:
            if not checkpoint_config:
                raise ValueError(
                    "LTX-2.3 training requires architecture metadata in checkpoint_path"
                )
            transformer_config = checkpoint_config.get("transformer", checkpoint_config)
            required = {
                "rope_type": "split",
                "cross_attention_adaln": True,
                "apply_gated_attention": True,
            }
            mismatched = {
                key: (transformer_config.get(key), expected)
                for key, expected in required.items()
                if transformer_config.get(key) != expected
            }
            if mismatched:
                raise ValueError(
                    f"checkpoint_path is not the expected LTX-2.3 architecture: {mismatched}"
                )
        return CausalLTXModelConfig.from_checkpoint_config(
            checkpoint_config,
            num_frame_per_block=self.config.num_frame_per_block,
            num_frame_per_block_first=self.config.num_frame_per_block_first,
            enable_causal_log_rescale=self.config.enable_causal_log_rescale,
        )

    def _make_wrapper(self, model):
        """Create CausalLTX2DiffusionWrapper from ODE config (avoids repetition)."""
        from ltx_causal import CausalLTX2DiffusionWrapper
        from ltx_core.model.transformer import checkpoint_fp8_module_names, convert_to_fp8_training

        if self.config.trainable_fp8_mode != "training":
            raise ValueError("Step 2 requires trainable_fp8_mode='training'")
        convert_to_fp8_training(
            model,
            checkpoint_fp8_module_names(self.config.checkpoint_path),
        )
        wrapper = CausalLTX2DiffusionWrapper(
            model=model,
            video_height=self.config.video_height,
            video_width=self.config.video_width,
            num_frame_per_block=self.config.num_frame_per_block,
            num_frame_per_block_first=self.config.num_frame_per_block_first,
            disable_causal_mask=self.config.disable_causal_mask,
        )
        wrapper.fp8_mode = "training"
        return wrapper

    @staticmethod
    def _assert_compatible_load(missing, unexpected, source: str) -> None:
        if missing or unexpected:
            raise RuntimeError(
                f"Incompatible causal checkpoint {source}: "
                f"missing={len(missing)} unexpected={len(unexpected)}; "
                f"missing_examples={list(missing)[:10]} "
                f"unexpected_examples={list(unexpected)[:10]}. "
                "Do not train with a partially loaded LTX-2.3 model."
            )

    @staticmethod
    def _strict_load(module: nn.Module, state_dict: dict, source: str) -> None:
        try:
            module.load_state_dict(state_dict, strict=True)
        except RuntimeError as exc:
            raise RuntimeError(
                f"Incompatible LTX-2.3 checkpoint: {source}. "
                "Legacy 6-way Step-2 checkpoints cannot initialize the corrected "
                "9-way/gated LTX-2.3 model."
            ) from exc

    def _load_models(self):
        """
        Load generator and text encoder models.

        Supported weight sources:
        1. Existing causal checkpoint (causal_model_checkpoint)
        2. Bidirectional DMD checkpoint remapped into the causal wrapper
        3. Original LTX-2 checkpoint as a fallback bootstrap
        """
        if self._generator is not None:
            return

        self._print("Loading models for ODE regression...")

        # Import causal model
        try:
            from ltx_causal import (
                CausalLTX2DiffusionWrapper,
                CausalLTXModel,
                CausalLTXModelConfig,
            )
        except ImportError:
            raise ImportError(
                "ltx-causal package not found. "
                "Please install it first: pip install -e packages/ltx-causal"
            )

        # Import text encoder
        from ltx_distillation.models.text_encoder_wrapper import create_text_encoder_wrapper

        # Load text encoder
        # Note: Requires checkpoint_path (LTX checkpoint) and gemma_path (text encoder)
        # If only text_encoder_checkpoint is provided, use it as gemma_path
        checkpoint_path = getattr(self.config, 'checkpoint_path', None)
        gemma_path = self.config.text_encoder_checkpoint

        if checkpoint_path is None:
            raise ValueError(
                "ODERegressionConfig requires 'checkpoint_path' (LTX-2 checkpoint) "
                "in addition to 'text_encoder_checkpoint' (Gemma path)"
            )

        text_encoder_device = (
            torch.device("cpu")
            if self.config.text_encoder_device == "cpu"
            else self.device
        )
        self._text_encoder = create_text_encoder_wrapper(
            checkpoint_path=checkpoint_path,
            gemma_path=gemma_path,
            device=text_encoder_device,
            dtype=self.dtype,
        )
        self._text_encoder.requires_grad_(False)
        self._text_encoder.eval()


        # Log causal mask setting
        if self.config.disable_causal_mask:
            self._print("ABLATION: causal mask DISABLED — fully bidirectional (original LTX-2)")
        else:
            self._print("Causal mask ENABLED")
        self._print(f"  enable_causal_log_rescale = {self.config.enable_causal_log_rescale}")

        # Load causal generator directly from checkpoints. Do not mutate loaded
        # weights with zeroinit / scaled / random branches.
        if self.config.causal_model_checkpoint:
            # Option 1: Load from existing causal checkpoint
            self._print(f"Loading causal model from: {self.config.causal_model_checkpoint}")
            model = CausalLTXModel(self._make_model_config())
            self._generator = self._make_wrapper(model).to(self.device, self.dtype)
            state_dict = self._load_checkpoint_state_dict(
                self.config.causal_model_checkpoint
            )
            state_dict = self._remap_state_dict_keys(state_dict)
            self._strict_load(
                self._generator,
                state_dict,
                self.config.causal_model_checkpoint,
            )

        elif self.config.bidirectional_model_checkpoint:
            # Option 2: Load from bidirectional DMD checkpoint
            # Causal model weights are compatible with bidirectional model
            self._print(f"Initializing from bidirectional model: {self.config.bidirectional_model_checkpoint}")

            # Create causal model architecture
            model = CausalLTXModel(self._make_model_config())
            self._generator = self._make_wrapper(model).to(self.device, self.dtype)

            # Load bidirectional weights
            bidirectional_state_dict = self._load_checkpoint_state_dict(
                self.config.bidirectional_model_checkpoint
            )

            # Remap state dict keys:
            # Bidirectional LTX2DiffusionWrapper uses X0Model which has:
            #   wrapper.model = X0Model, X0Model.velocity_model = LTXModel
            # So keys are: model.velocity_model.xxx
            # Causal CausalLTX2DiffusionWrapper uses:
            #   wrapper.model = CausalLTXModel
            # So keys should be: model.xxx
            state_dict = self._remap_state_dict_keys(bidirectional_state_dict)

            # Load with strict=False (causal model has KV cache-related keys)
            self._strict_load(
                self._generator,
                state_dict,
                self.config.bidirectional_model_checkpoint,
            )
            self._print("Loaded bidirectional weights with full architecture compatibility")

            # For eval-time bootstrap rounds, use the exact original bidirectional
            # wrapper instead of rebuilding one from the causal model config.
            from ltx_distillation.models.ltx_wrapper import create_ltx2_wrapper

            delegate = create_ltx2_wrapper(
                checkpoint_path=self.config.checkpoint_path,
                gemma_path=self.config.text_encoder_checkpoint,
                device=torch.device("cpu"),
                dtype=self.dtype,
                fp8_mode="static",
            )
            delegate.load_state_dict(bidirectional_state_dict, strict=True)
            delegate.eval()
            self._generator.set_bidirectional_delegate(delegate)

        elif self.config.checkpoint_path:
            # Option 3: Load from original LTX-2 checkpoint as fallback
            self._print(f"Initializing from original LTX-2 checkpoint: {self.config.checkpoint_path}")

            model = CausalLTXModel(self._make_model_config())
            self._generator = self._make_wrapper(model).to(self.device, self.dtype)

            # Load original weights (keys are raw LTXModel keys without prefix)
            state_dict = self._load_checkpoint_state_dict(
                self.config.checkpoint_path
            )
            state_dict = self._remap_state_dict_keys(state_dict)

            self._strict_load(self._generator, state_dict, self.config.checkpoint_path)
            self._print("Loaded original LTX-2 weights with full architecture compatibility")

        else:
            raise ValueError(
                "ODERegressionConfig requires one checkpoint source: "
                "set causal_model_checkpoint, bidirectional_model_checkpoint, "
                "or checkpoint_path."
            )

        self._verify_weights_loaded()
        self._print("[Checkpoint Load] Model weights loaded and validated.")

        # Set gradient requirements
        self._generator.requires_grad_(True)

        if self.config.gradient_checkpointing:
            self._generator.enable_gradient_checkpointing()

        self._print("Models loaded for ODE regression.")

    def _move_conditioning_to_device(
        self,
        conditional_dict: Dict[str, torch.Tensor],
    ) -> Dict[str, torch.Tensor]:
        return {
            key: value.to(device=self.device, dtype=self.dtype, non_blocking=True)
            if torch.is_tensor(value)
            else value
            for key, value in conditional_dict.items()
        }

    @staticmethod
    def _load_checkpoint_config(checkpoint_path: str) -> dict:
        """Read model config stored in a safetensors checkpoint metadata."""
        if not checkpoint_path:
            return {}
        from ltx_causal.checkpoint import load_checkpoint_config

        return load_checkpoint_config(checkpoint_path)

    @staticmethod
    def _load_checkpoint_state_dict(checkpoint_path: str) -> dict:
        """Load state dict from a checkpoint file (safetensors or .pt)."""
        from ltx_causal.checkpoint import load_checkpoint_state_dict

        return load_checkpoint_state_dict(checkpoint_path)

    @staticmethod
    def _fold_prequantized_fp8_scales(state_dict: dict) -> dict:
        """Reconstruct Student optimizer master weights from static FP8 tensors.

        LTX-2.3 FP8 checkpoints store a quantized tensor alongside a scalar
        ``*_scale`` tensor. AdamW updates a BF16 master; after loading, torchao
        performs the Student Linear forward/backward GEMMs in FP8.
        """
        from ltx_causal.checkpoint import fold_prequantized_fp8_scales

        return fold_prequantized_fp8_scales(state_dict)

    # Prefixes in the full LTX-2 checkpoint that are NOT transformer weights.
    # These must be filtered out when loading into the causal model.
    # Note: audio_embeddings_connector and video_embeddings_connector are text
    # encoder components stored under model.diffusion_model.* in the full
    # checkpoint (loaded by AVGemmaTextEncoderModel via SDOps), NOT part of LTXModel.
    _NON_TRANSFORMER_PREFIXES = (
        "vae.", "audio_vae.", "vocoder.",
        "model.vae.", "model.audio_vae.", "model.vocoder.",
    )
    # Additional prefixes to filter AFTER remapping model.diffusion_model.* → model.*
    _NON_TRANSFORMER_REMAPPED_PREFIXES = (
        "model.audio_embeddings_connector.",
        "model.video_embeddings_connector.",
    )

    @staticmethod
    def _remap_state_dict_keys(state_dict: dict, *, preserve_fp8: bool = False) -> dict:
        """Map an LTX checkpoint to CausalLTX2DiffusionWrapper keys."""
        from ltx_causal.checkpoint import remap_transformer_state_dict

        return remap_transformer_state_dict(
            state_dict,
            target_prefix="model.",
            preserve_fp8=preserve_fp8,
        )

    @staticmethod
    def _legacy_remap_state_dict_keys(state_dict: dict) -> dict:
        """Remap state dict keys to match CausalLTX2DiffusionWrapper structure.

        Handles four source formats:
        1. Raw LTXModel keys: "patchify_proj.weight", "transformer_blocks.0.xxx"
           → Need to add "model." prefix
        2. Bidirectional wrapper keys: "model.velocity_model.transformer_blocks.0.xxx"
           → Need to remap "model.velocity_model." to "model."
        3. Causal wrapper keys: "model.transformer_blocks.0.xxx"
           → Already correct, no remapping needed
        4. Full checkpoint keys: "model.diffusion_model.patchify_proj.weight"
           → Filter to only "model.diffusion_model.*", remap to "model.*"
           (Also contains vae.*, audio_vae.*, vocoder.* which must be discarded)

        Target: "model.transformer_blocks.0.xxx" (CausalLTX2DiffusionWrapper.model = CausalLTXModel)
        """
        if not state_dict:
            return state_dict

        state_dict = LTX2ODERegression._fold_prequantized_fp8_scales(state_dict)

        # Check if this is a full checkpoint (contains model.diffusion_model.* keys)
        # We check a sample of keys rather than just the first one, because key
        # ordering in safetensors depends on how the file was created.
        sample_keys = list(state_dict.keys())[:20]
        has_diffusion_model = any(
            k.startswith("model.diffusion_model.") for k in sample_keys
        )
        if not has_diffusion_model:
            # Also check if any key matches (for small state dicts)
            has_diffusion_model = any(
                k.startswith("model.diffusion_model.") for k in state_dict
            )

        if has_diffusion_model:
            # Format 4: Full checkpoint with model.diffusion_model.* prefix
            # Filter to only transformer keys and remap:
            #   model.diffusion_model.xxx → model.xxx
            # Also filter out text encoder components stored under this prefix:
            #   model.diffusion_model.audio_embeddings_connector.* (AVGemmaTextEncoderModel)
            #   model.diffusion_model.video_embeddings_connector.* (AVGemmaTextEncoderModel)
            print("  Remapping full checkpoint keys: model.diffusion_model.* → model.*")
            remapped = {}
            skipped = 0
            for k, v in state_dict.items():
                if k.startswith("model.diffusion_model."):
                    new_key = "model." + k[len("model.diffusion_model."):]
                    # Filter text encoder components that are NOT part of the transformer
                    if any(new_key.startswith(p) for p in LTX2ODERegression._NON_TRANSFORMER_REMAPPED_PREFIXES):
                        skipped += 1
                        continue
                    remapped[new_key] = v
                # Skip non-transformer keys (vae.*, audio_vae.*, vocoder.*, etc.)
            if skipped > 0:
                print(f"  Filtered {skipped} text encoder keys (embeddings_connector)")
            return remapped

        # Check first key to detect remaining formats
        first_key = next(iter(state_dict))

        if first_key.startswith("model.velocity_model."):
            # Format 2: Bidirectional wrapper (X0Model inside)
            # model.velocity_model.xxx → model.xxx
            print("  Remapping bidirectional keys: model.velocity_model.* → model.*")
            remapped = {}
            for k, v in state_dict.items():
                if k.startswith("model.velocity_model."):
                    new_key = "model." + k[len("model.velocity_model."):]
                    remapped[new_key] = v
                # Skip non-transformer keys
            return remapped

        elif first_key.startswith("model."):
            # Format 3: Already causal wrapper format
            # Still filter out any non-transformer keys that might be present
            has_non_transformer = any(
                k.startswith(p) for k in state_dict
                for p in LTX2ODERegression._NON_TRANSFORMER_PREFIXES
            )
            if has_non_transformer:
                return {
                    k: v for k, v in state_dict.items()
                    if not any(k.startswith(p) for p in LTX2ODERegression._NON_TRANSFORMER_PREFIXES)
                }
            return state_dict

        else:
            # Format 1: Raw LTXModel keys (from extracted checkpoint)
            # xxx → model.xxx, but filter out non-transformer keys
            print("  Remapping raw LTX keys: * → model.*")
            return {
                "model." + k: v for k, v in state_dict.items()
                if not any(k.startswith(p) for p in LTX2ODERegression._NON_TRANSFORMER_PREFIXES)
            }

    def _verify_weights_loaded(self):
        """Verify critical parameters were loaded from checkpoint.

        Checks scale_shift_table and other key parameters for:
        - Extreme values (sign of torch.empty garbage)
        - NaN/Inf values
        - Zero values (sign of failed initialization)
        """
        problems = []
        for name, param in self._generator.named_parameters():
            pf = param.data.float()

            # Check for NaN/Inf
            if pf.isnan().any():
                problems.append(f"  NaN: {name} ({pf.isnan().sum().item()} NaN values)")
            if pf.isinf().any():
                problems.append(f"  Inf: {name} ({pf.isinf().sum().item()} Inf values)")

            # Check scale_shift_table parameters for extreme values
            # These are initialized with torch.empty() and should be small after loading
            if "scale_shift_table" in name:
                max_val = pf.abs().max().item()
                if max_val > 100:
                    problems.append(
                        f"  EXTREME: {name} max_abs={max_val:.2e} "
                        f"(expected <10, may be uninitialized torch.empty garbage)"
                    )
                self._print(f"  [Weight Check] {name}: shape={list(param.shape)} "
                      f"min={pf.min().item():.4f} max={pf.max().item():.4f} "
                      f"mean={pf.mean().item():.4f} std={pf.std().item():.4f}")

        if problems:
            raise RuntimeError(
                "Loaded checkpoint contains invalid or uninitialized parameters:\n"
                + "\n".join(problems)
            )
        self._print("[Weight Check] All parameters look OK (no NaN/Inf/extreme values)")

    @property
    def generator(self) -> nn.Module:
        """Get the generator model (lazy loading)."""
        self._load_models()
        return self._generator

    @property
    def text_encoder(self) -> nn.Module:
        """Get the text encoder (lazy loading)."""
        self._load_models()
        return self._text_encoder

    def set_module_grad(self, module_grad: Dict[str, bool]) -> None:
        """Set gradient requirements for modules."""
        if module_grad.get("generator", True):
            self.generator.requires_grad_(True)
        else:
            self.generator.requires_grad_(False)
            self.generator.eval()

    def enable_gradient_checkpointing(self) -> None:
        """Enable gradient checkpointing for memory efficiency."""
        self.generator.enable_gradient_checkpointing()

    def _process_timestep(self, timestep: torch.Tensor) -> torch.Tensor:
        """
        Process timestep based on generator task type and uniform_timestep setting.

        Args:
            timestep: [B, F] tensor of timestep indices

        Returns:
            Processed timestep tensor
        """
        # If uniform_timestep is enabled, all frames use the same noise level
        if self.config.uniform_timestep:
            return timestep[:, :1].expand_as(timestep).contiguous()

        if self.config.generator_task == "bidirectional_video":
            # Broadcast first timestep to all frames
            return timestep[:, :1].expand_as(timestep).contiguous()

        elif self.config.generator_task == "causal_video":
            # Make timesteps uniform within each block.
            # Block layout (4-3-3-3-...):
            #   Block 0: frames [0, num_frame_per_block_first)
            #   Block k>=1: frames [first + (k-1)*block_size, first + k*block_size)
            # Timestep grouping must match this exactly.
            B, num_frames = timestep.shape
            first_block = self.config.num_frame_per_block_first
            block_size = self.num_frame_per_block

            if num_frames <= 1:
                return timestep

            result = timestep.clone()

            # Block 0: all frames share first frame's timestep
            end0 = min(first_block, num_frames)
            result[:, :end0] = timestep[:, :1].expand(B, end0)

            # Remaining blocks: group by block_size
            idx = end0
            while idx < num_frames:
                end = min(idx + block_size, num_frames)
                result[:, idx:end] = timestep[:, idx:idx + 1].expand(B, end - idx)
                idx = end

            return result

        else:
            raise NotImplementedError(f"Unknown task: {self.config.generator_task}")

    @torch.no_grad()
    def _prepare_generator_input(
        self,
        video_latent: torch.Tensor,
        audio_latent: Optional[torch.Tensor] = None,
        sigmas: Optional[torch.Tensor] = None,
    ) -> Tuple[torch.Tensor, Optional[torch.Tensor], torch.Tensor]:
        """
        Prepare inputs for generator from ODE trajectories.

        Randomly selects intermediate timesteps from the trajectory.

        Args:
            video_latent: [B, T, F, C, H, W] video ODE trajectory
            audio_latent: [B, T, F_a, C] audio ODE trajectory (optional)
            sigmas: [B, T] actual sigma values per trajectory entry (from LTX2Scheduler).
                    If None, falls back to denoising_step_list / 1000.0

        Returns:
            (noisy_video, noisy_audio, sigma) tuple where sigma is [B, F_v] actual sigma values
        """
        B, T, F_v, C_v, H, W = video_latent.shape

        # Randomly choose timestep index for each frame
        # T is number of denoising steps in trajectory (includes clean at T-1)
        # Following CausVid: sample all indices including clean, mask loss at sigma=0
        index = torch.randint(
            0, T,
            [B, F_v],
            device=self.device,
            dtype=torch.long,
        )

        # Process timestep for causal/bidirectional
        index = self._process_timestep(index)

        # Gather video latents at selected timesteps
        # video_latent: [B, T, F, C, H, W]
        # index: [B, F]
        noisy_video = torch.gather(
            video_latent,
            dim=1,
            index=index.reshape(B, 1, F_v, 1, 1, 1).expand(-1, -1, -1, C_v, H, W),
        ).squeeze(1)  # [B, F, C, H, W]

        # Get actual sigma values for the selected trajectory indices
        if sigmas is not None:
            # Use actual sigma values from data (preferred)
            # sigmas: [B, T], index: [B, F_v] → sigma: [B, F_v]
            sigma = torch.gather(sigmas, dim=1, index=index)
        else:
            # Fallback: use denoising_step_list / 1000.0 (legacy, linear mapping)
            timestep = self.denoising_step_list[index]  # [B, F]
            sigma = timestep.to(self.dtype) / 1000.0

        # Handle audio
        noisy_audio = None
        if audio_latent is not None:
            B, T, F_a, C_a = audio_latent.shape
            audio_index = self._expand_video_blocks_to_audio(
                index,
                F_a,
                value_name="trajectory index",
            )

            noisy_audio = torch.gather(
                audio_latent,
                dim=1,
                index=audio_index.reshape(B, 1, F_a, 1).expand(-1, -1, -1, C_a),
            ).squeeze(1)  # [B, F_a, C]

        return noisy_video, noisy_audio, sigma

    def _expand_video_blocks_to_audio(
        self,
        values: torch.Tensor,
        audio_frames: int,
        *,
        value_name: str,
    ) -> torch.Tensor:
        """Expand block-uniform video values to the aligned audio blocks."""
        if values.ndim != 2:
            raise ValueError(f"Expected {value_name} with shape [B, F_v], got {tuple(values.shape)}")

        batch_size, video_frames = values.shape
        blocks = compute_av_blocks(
            total_video_latent_frames=video_frames,
            num_frame_per_block=self.config.num_frame_per_block,
            num_frame_per_block_first=self.config.num_frame_per_block_first,
        )
        expected_audio_frames = blocks[-1].audio_end
        if audio_frames != expected_audio_frames:
            raise ValueError(
                "Audio trajectory does not match the causal AV block layout: "
                f"got F_a={audio_frames}, expected {expected_audio_frames} for F_v={video_frames}"
            )

        expanded = values.new_empty((batch_size, audio_frames))
        for block in blocks:
            video_block = values[:, block.video_start : block.video_end]
            reference = video_block[:, :1]
            if not torch.equal(video_block, reference.expand_as(video_block)):
                raise ValueError(
                    f"Video {value_name} is not uniform in causal block {block.block_idx}: "
                    f"video=[{block.video_start}:{block.video_end}]"
                )
            expanded[:, block.audio_start : block.audio_end] = reference
        return expanded

    def _expand_video_sigma_to_audio(
        self,
        sigma: torch.Tensor,
        F_a: int,
    ) -> torch.Tensor:
        """Expand video-frame sigma [B, F_v] to audio-frame sigma [B, F_a]."""
        return self._expand_video_blocks_to_audio(
            sigma,
            F_a,
            value_name="sigma",
        )

    def _expand_video_mask_to_audio(
        self,
        mask: torch.Tensor,
        F_a: int,
    ) -> torch.Tensor:
        """Expand video-frame mask [B, F_v] to audio-frame mask [B, F_a]."""
        return self._expand_video_blocks_to_audio(
            mask,
            F_a,
            value_name="loss mask",
        )

    @staticmethod
    def _x0_to_velocity(
        pred_x0: torch.Tensor,
        noisy: torch.Tensor,
        sigma: torch.Tensor,
    ) -> torch.Tensor:
        """Convert x0 predictions back to flow/velocity predictions."""
        return (
            (noisy.to(torch.float32) - pred_x0.to(torch.float32))
            / sigma.to(torch.float32)
        ).to(pred_x0.dtype)

    @staticmethod
    def _masked_mse_per_sample(
        pred: torch.Tensor,
        target: torch.Tensor,
        mask: torch.Tensor,
    ) -> torch.Tensor:
        """Compute per-sample masked MSE with stable normalization."""
        pred_f = pred.to(torch.float32)
        target_f = target.to(torch.float32)
        mask_f = mask.to(torch.float32)
        diff_sq = (pred_f - target_f).pow(2) * mask_f
        reduce_dims = tuple(range(1, diff_sq.ndim))
        denom = mask_f.sum(dim=reduce_dims).clamp(min=1.0)
        return diff_sq.sum(dim=reduce_dims) / denom

    def generator_loss(
        self,
        video_latent: torch.Tensor,
        conditional_dict: Dict[str, torch.Tensor],
        audio_latent: Optional[torch.Tensor] = None,
        sigmas: Optional[torch.Tensor] = None,
        return_samples: bool = False,
    ) -> Tuple[torch.Tensor, Dict[str, Any]]:
        """
        Compute ODE regression loss for generator training.

        Loss: MSE(pred_x0, target_x0), same as CausVid.
        The wrapper converts velocity→x0 internally (x0 = x_t - v * sigma),
        so we directly compare predicted x0 with target x0.

        Args:
            video_latent: [B, T, F, C, H, W] video ODE trajectory (noise→clean)
            conditional_dict: Text conditioning dictionary
            audio_latent: [B, T, F_a, C] audio ODE trajectory (optional)
            sigmas: [B, T] actual sigma values per trajectory entry (from LTX2Scheduler).
                    If None, falls back to denoising_step_list / 1000.0
            return_samples: If True, include predicted and target latents in log_dict

        Returns:
            (loss, log_dict) tuple where log_dict contains debugging info
        """
        # Target is the last (clean) latent in trajectory
        target_video = video_latent[:, -1]  # [B, F, C, H, W]
        target_audio = audio_latent[:, -1] if audio_latent is not None else None

        # Prepare noisy inputs — returns actual sigma values [B, F_v]
        noisy_video, noisy_audio, sigma = self._prepare_generator_input(
            video_latent=video_latent,
            audio_latent=audio_latent,
            sigmas=sigmas,
        )

        # sigma is already in [0, 1] range (actual sigma values from LTX2Scheduler)
        # Keep sigma as float32 for precise loss computation (division by sigma).
        # The model wrapper handles dtype conversion internally.
        sigma = sigma.to(torch.float32)  # [B, F_v]

        # Compute audio sigma aligned with video (also float32)
        audio_sigma = None
        if noisy_audio is not None:
            audio_sigma = self._expand_video_sigma_to_audio(sigma, noisy_audio.shape[1])

        # Run generator — wrapper returns x0 predictions (velocity→x0 conversion
        # is done inside CausalLTX2DiffusionWrapper: x0 = x_t - velocity * sigma).
        # use_causal_timestep=False because _prepare_generator_input already made
        # sigma values block-uniform via _process_timestep.
        pred_x0_video, pred_x0_audio = self.generator(
            noisy_image_or_video=noisy_video,
            conditional_dict=conditional_dict,
            timestep=sigma.to(self.dtype),
            noisy_audio=noisy_audio,
            audio_timestep=audio_sigma.to(self.dtype) if audio_sigma is not None else None,
            use_causal_timestep=False,
        )
        pred_video = pred_x0_video
        pred_audio = pred_x0_audio

        # === Forward pass diagnostics (rank 0 only) ===
        should_diag = self._diag_step < 10 or self._diag_step % 50 == 0
        if should_diag and self.diag_logger:
            log = self.diag_logger
            def _ts(name, t):
                tf = t.float()
                return (f"  {name:35s} shape={str(list(t.shape)):25s} "
                        f"min={tf.min().item():>12.4e} max={tf.max().item():>12.4e} "
                        f"mean={tf.mean().item():>12.4e} std={tf.std().item():>12.4e} "
                        f"nan={tf.isnan().any().item()} inf={tf.isinf().any().item()}")
            log.info("")
            log.info(f"--- FORWARD PASS TENSOR STATS (diag_step={self._diag_step}) ---")
            log.info(_ts("noisy_video", noisy_video))
            log.info(_ts("target_video", target_video))
            log.info(_ts("sigma", sigma))
            log.info(f"  {'sigma values':35s} {sigma.tolist()}")
            log.info(f"  {'uniform_timestep':35s} {self.config.uniform_timestep}")
            log.info(_ts("pred_x0_video", pred_video))
            if noisy_audio is not None:
                log.info(_ts("noisy_audio", noisy_audio))
                log.info(_ts("audio_sigma", audio_sigma))
            if pred_audio is not None:
                log.info(_ts("pred_x0_audio", pred_audio))
            for b in range(pred_video.shape[0]):
                vf = pred_video[b].float()
                log.info(f"  sample[{b}] x0_video norm={vf.norm().item():.4e} "
                         f"mean={vf.mean().item():.4e} std={vf.std().item():.4e}")
        self._diag_step += 1

        # Mask: only compute loss on non-zero sigma (sigma=0 means already clean, no denoising)
        mask = sigma > 1e-6  # [B, F_v]

        # === x0 prediction loss (CausVid-style) ===
        # The wrapper already converts velocity→x0 internally, so we directly
        # compare pred_x0 with target_x0. No extra conversion needed.
        # (pred_video / pred_audio already set above from generator output)

        # Diagnostics
        if should_diag and self.diag_logger:
            log = self.diag_logger
            def _ts2(name, t):
                tf = t.float()
                return (f"  {name:35s} shape={str(list(t.shape)):25s} "
                        f"min={tf.min().item():>12.4e} max={tf.max().item():>12.4e} "
                        f"mean={tf.mean().item():>12.4e} std={tf.std().item():>12.4e}")
            log.info("")
            log.info("--- X0 LOSS (wrapper already converts velocity→x0) ---")
            log.info(_ts2("pred_x0_video", pred_video))
            log.info(_ts2("target_video", target_video))
            diff = (pred_video - target_video).float()
            log.info(_ts2("pred - target", diff))
            mse_per_sample = diff.pow(2).mean(dim=[1, 2, 3, 4])
            log.info(f"  {'MSE per sample':35s} {[f'{v:.6e}' for v in mse_per_sample.tolist()]}")

        # Video x0 loss
        video_mask = mask.unsqueeze(-1).unsqueeze(-1).unsqueeze(-1).expand_as(pred_video)
        if mask.any():
            video_loss = F.mse_loss(
                pred_video[video_mask],
                target_video[video_mask],
                reduction="mean",
            )
            unnormalized_loss = self._masked_mse_per_sample(
                pred_video,
                target_video,
                video_mask,
            )
        else:
            # Keep video computation graph alive for FSDP all-reduce
            video_loss = (pred_video * 0.0).sum()
            unnormalized_loss = self._masked_mse_per_sample(
                pred_video,
                target_video,
                video_mask,
            )

        # Audio x0 loss
        audio_loss = (pred_audio * 0.0).sum() if pred_audio is not None else (pred_video * 0.0).sum()
        if pred_audio is not None and target_audio is not None:
            audio_mask = self._expand_video_mask_to_audio(mask, pred_audio.shape[1])
            if audio_mask.any():
                amask = audio_mask.unsqueeze(-1).expand_as(pred_audio)
                audio_loss = F.mse_loss(
                    pred_audio[amask],
                    target_audio[amask],
                    reduction="mean",
                )

        # Combined loss with configurable weights
        # video_loss_weight=1.0, audio_loss_weight=0.0 → video only (default)
        # audio_loss_weight>0 → audio loss participates in gradient
        v_w = self.config.video_loss_weight
        a_w = self.config.audio_loss_weight
        if a_w > 0:
            loss = v_w * video_loss + a_w * audio_loss
        else:
            loss = v_w * video_loss

        # Log dict
        log_dict = {
            "video_loss": video_loss.detach(),
            "audio_loss": audio_loss.detach() if audio_latent is not None else None,
            "timestep": sigma.mean(dim=1).detach(),
            "loss_target": self.config.loss_target,
            "unnormalized_loss": unnormalized_loss.detach(),
        }

        # Include sample tensors for visualization (detached)
        if return_samples:
            if pred_video is not None:
                log_dict["pred_video"] = pred_video.detach()
            log_dict["target_video"] = target_video.detach()
            log_dict["noisy_video"] = noisy_video.detach()
            if pred_audio is not None:
                log_dict["pred_audio"] = pred_audio.detach()
            if target_audio is not None:
                log_dict["target_audio"] = target_audio.detach()

        return loss, log_dict

    def forward(
        self,
        video_latent: torch.Tensor,
        conditional_dict: Dict[str, torch.Tensor],
        audio_latent: Optional[torch.Tensor] = None,
        sigmas: Optional[torch.Tensor] = None,
    ) -> Tuple[torch.Tensor, Dict[str, Any]]:
        """Forward pass computes generator loss."""
        return self.generator_loss(
            video_latent=video_latent,
            conditional_dict=conditional_dict,
            audio_latent=audio_latent,
            sigmas=sigmas,
        )
